const FA = {
    status: {
        active: 'فعال',
        completed: 'انجام شده',
        inactive: 'غیرفعال',
        banned: 'مسدود شده',
        pending: 'در انتظار متقاضی',
        processing: 'در حال اجرا',
        left: 'مسافر مبدا رو ترک کرد',
        arrived: 'مسافر به مقصد رسید',
        pickedUp: 'مسافر به محل اقامت رسید',
        canceled: 'کنسل شده',
        done: 'انجام شده',
        approved: 'تایید شده',
        rejected: 'رد شده',
        draft: 'پیش نویس',
        published: 'منتشر شده',
        underReview: 'در حال بررسی',
        waitingOnClient: 'در انتظار متقاضی',
        waitingOnUser: 'در انتظار کارشناس',
        deleted: 'حذف شده',
        closed: 'بسته شده',
        NA: 'نامشخص',
    },
    role: {
        admin: 'ادمین',
        consultant: 'مشاور',
        executive: 'کارشناس اجرا',
        chief_executive: 'مدیر اجرایی',
    },
    paymentType: {
        initialPayment: 'پیش پرداخت',
        paymentCompletion: 'تکمیل وجه',
        appilicationFee: 'هزینه ثبت نام',
        visaFee: 'هزینه ویزا',
        contractFee: 'هزینه قرارداد',
        translationFee: 'هزینه ترجمه',
        languageCourseFee: 'هزینه دوره زبان',
        russianVisa: 'ویزا روسیه',
        deliveryFee: 'هزینه پیک',
        tomerFee: 'هزینه تومر',
        HSKFee: 'هزینه HSK',
        tolkFee: 'هزینه تولک',
        blueDiploma: 'دیپلم آبی',
        tuitionFee: 'شهریه دانشگاه',
        leaderFee: 'خدمات لیدری',
        otherFee: 'هزینه های دیگر',
        returned: 'بازگشت داده شده',
    },
    paymentMethod: {
        direct: 'پرداخت نقدی',
        deposit: 'واریز به حساب',
        POS: 'دستگاه کارتخوان',
    },
    currency: {
        USD: 'دلار آمریکا',
        EUR: 'یورو',
        IRT: 'تومان',
    },
    visaType: {
        student: 'دانشجویی',
        work: 'کاری',
        tourist: 'توریستی',
        business: 'تجاری',
        other: 'دیگر',
    },
    invLetterType: {
        JW201: 'JW201',
        JW202: 'JW202',
        RussiaLetter: 'دعوتنامه روسیه',
        RomaniaLetter: 'تاییدیه تحصیلی رومانی',
        personal: 'شخصی',
        tourist: 'توریستی',
        commercial: 'تجاری',
    },
    fileType: {
        sound: 'فایل صوتی',
        video: 'فایل ویدیو',
        image: 'عکس',
        document: 'سند',
    },
    priority: {
        high: 'زیاد',
        medium: 'متوسط',
        low: 'کم',
    },
};

export default FA;
